[package]
name = "rust_app"
version = "0.1.0"
edition = "2024"

[dependencies]
amqprs = "2.1.3"
tokio = { version = "1.49.0", features = ["full"] }
log = "0.4.29"
env_logger = "0.11.8"
anyhow = "1.0.101"
async-trait = "0.1.89"